### ISSUE TITLE
Select categories is broken

### ISSUE THREAD

**Issue by caharding** [ushahidi/platform#1248]
### Steps to reproduce the behaviour/error
Create a category, select it

<img width="343" alt="screen shot 2016-06-21 at 4 20 46 pm" src="https://cloud.githubusercontent.com/assets/1618793/16249628/2fd7cec0-37cc-11e6-9380-92db2a31c57c.png">

**Comment by rjmackay** [comment]
Is the issue just the + icon on top of everything?

**Comment by jshorland** [comment]
Failed testing. When I select a category, the + icon is still on top of the text. 

Steps to reproduce:
1. login to jshorland88.ushahidi.io (jess@ushahidi.io, password)
2. navigate to settings --> categories
3. select category
4. See screenshot

**Comment by willdoran** [comment]
Sorry I seem to have fundamentally misunderstood how the acceptance testing element works. I need look at how this change can be branched from PL before I can land it.

**Comment by rjmackay** [comment]
This should be fixed on all ushahididev.com sites. I'll push to production (ushahidi.io) soon too.

**Comment by rjmackay** [comment]
@caharding Can you retest this when you get a chance?

**Comment by caharding** [comment]
Yeah, not resolved unfortunately, the dropdown needs to start at the top of the pg 70px above where it is now. 

<img width="1280" alt="screen shot 2016-07-19 at 2 03 31 pm" src="https://cloud.githubusercontent.com/assets/1618793/16966513/b82e049e-4db9-11e6-8b74-7c73d9cde4d7.png">

**Comment by rjmackay** [comment]
.. no thats expected as per the PL http://preview.ushahidi.com/platform-pattern-library/master/assets/html/5_layouts/settings-categories.html
I'm closing this since the original issue of the (+) icon has been fixed. If you think there's an additional issue, log it on the PL.
