### ISSUE TITLE
Bug for Categories

### ISSUE THREAD

**Issue by filantropiintern** [ushahidi/platform#1501]
### Expected behaviour
There will be "categories" option everytime we want to inputting data on surveys
### Actual behaviour
Sometimes the "Categories" option went missing
### Steps to reproduce the behaviour/error

**Comment by jshorland** [comment]
@filantropiintern Are you still experiencing this issue? We believe it is a caching issue.

**Comment by filantropiintern** [comment]
Unfortunately, yes, and the time span between the disappearance to appearing again is now about 10 to 15 minutes




---- On Tue, 20 Dec 2016 07:14:14 +0700 Jess Shorland &lt;notifications@github.com&gt; wrote ----




@filantropiintern Are you still experiencing this issue? We believe it is a caching issue.

**Comment by rjmackay** [comment]
Cache time is set to 15 mins I think. My guess is that theres a race condition somewhere such that sometimes categories isn't populated in the view..

**Comment by rjmackay** [comment]
Closing in favour of #1569

**Comment by rjmackay** [comment]
Actually this seem subtly different so I'll leave it open

**Comment by Angamanga** [comment]
Related to  #1569 and #1505, fixed in #465

**Comment by jshorland** [comment]
Still having a hard time duplicating anywhere. Can anyone help me try to QA this? @natmanning @aoduor

**Comment by aoduor** [comment]
Yeah, sure @jshorland. I'll test this and share a gif to demonstrate in abit.

**Comment by aoduor** [comment]
@jshorland this looks to be fixed now. I wasn't able to replicate.

**Comment by Angamanga** [comment]
@jshorland you can test here: qa.ushahididev.com

**Comment by jshorland** [comment]
Fixed on qa.ushahididev.com. Ready to deploy (if not already deployed)
