### ISSUE TITLE
CSV export request fails for jobs that are requesting a CSV header

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#2637]
### Expected behaviour
A request for CSV using a URL such as `GET http://csvexportsforever.api.v3-qa.ush.zone/api/v3/exports/external/cli/57?limit=200&offset=0&include_header=1&api_key=.......` should initiate the generation of a small CSV file with headers.

### Actual behaviour
This request results in a `500 Internal Server Error` response with the following payload:
{"errors":[{"status":"Notice","title":"Array to string conversion","message":"Array to string conversion"}]}

### Note
This issue only happens when include_header=1. 
Requests with include_header=0 don't result in this error message.

#### Where does this issue happen?
- [ ] http://csvexportsforever.v3-qa.ush.zone/

**Comment by rjmackay** [comment]
I messed this up yesterday. I didn't push changes to develop to stop it deploying to QA. So the most recent changes on develop got deployed to QA - that could be what broke this. Certainly you were probably testing the wrong commit. Sorry!

**Comment by rjmackay** [comment]
How would I reproduce this myself?

**Comment by rowasc** [comment]
It's solved now. I just got a successful CSV

**Comment by rowasc** [comment]
@kinstelli should we close this?

**Comment by kinstelli** [comment]
@rowasc 
Some bad news: I'm afraid I'm still seeing this error for _some_ of the csv requests. 

I get the impression that this might only happen with certain types of data during the process of converting it into CSV format. 

Here is the most recent one. More strangely, this is not a request with include_header=1:

```
http://csvexportsforever.api.v3-qa.ush.zone/api/v3/exports/external/cli/63?limit=200&offset=800&include_header=&api_key=xxxxxxxxxxxxxx 
```

```
...resulted in a `500 Internal Server Error` response:
{"errors":[{"status":"Notice","title":"Array to string conversion","message":"Array to string conversion"}]}
```

**Comment by kinstelli** [comment]
For reference: according to the logs on the deployment, the array-to-string issue happens here.

 EMERGENCY: ErrorException [ 8 ]: Array to string conversion ~ (APPPATH/classes/Ushahidi/Formatter/Post/CSV.php [ 106 ]) (https://github.com/ushahidi/platform/blob/c916f4ad7e437067028f00c4d8740db89e9e3c62/application/classes/Ushahidi/Formatter/Post/CSV.php#L106)

**Comment by kinstelli** [comment]
@rowasc, @willdoran   - Any thoughts on what we ought to write to the CSV if one of the elements of `$values` is also an array?  

Could we just `implode()` this into a single string? Or is it theoretically possible that we'll have several levels of arrays?

**Comment by rowasc** [comment]
@kinstelli this sounds like there is an issue before we get here, at "getValueForRecord". At this point, the values should all be sane and ready to be inserted. I can take a look when I wake up (it's a bit late now) , in case you want to assign it to me since I know this part and it's probably my own bug anyway

**Comment by kinstelli** [comment]
Okay, if you know it well and seems quick to fix, I'll tag you here, but if not I can try and work on it tomorrow.

**Comment by willdoran** [comment]
@rowasc @kinstelli I have confusing news, the above example passed for me :(
Could it be failing intermittently? I used the id 63, was this right?

**Comment by rowasc** [comment]
Posting the information we have now: 
- The database in csvexportsforever is BROKEN. There are  many records pointing to invalid form attributes (ie form attribute id 999, but that attribute does not exist) and there are records of lat/lon (and possibly other fields) associated with text fields. This creates a problem with the csv getRecordForValue function that maps values to their format. 
- We should fix the DB so we can continue testing. 

Status: 
- I generated a csv that should be good enough as a starting point for importing a survey with multiple fields, but I'm having issues to actually import it. I spent a couple hours trying to do this and keep having issues so I am probably doing something wrong
@kinstelli  If you can , ping me to sync over this and we can work on next steps together to fix the deployment.

**Comment by rowasc** [comment]
<img width="502" alt="screen shot 2018-03-30 at 12 00 49 pm" src="https://user-images.githubusercontent.com/2434401/38150868-62edc8dc-3437-11e8-84da-200dfe5f6ec8.png">
Screenshot of a record with a point field matched to text

**Comment by kinstelli** [comment]
This appears to work now. This should be implicitly QAd as described in other tickets, so I'm closing it.
