### ISSUE TITLE
If targeted survey has no more outgoing questions, server responds with Error 400 to last incoming message

### ISSUE THREAD

**Issue by kinstelli** [ushahidi/platform#2797]
### Expected behaviour
- HTTP should respond with 200, then just not send another message to the recipient

### Actual behaviour
- HTTP responds with 400
```
{
    "errors": [
        {
            "status": 400,
            "title": "Outgoing question not found for contact 2 and form 3",
            "message": "Outgoing question not found for contact 2 and form 3"
        }
    ]
}
```

### Steps to reproduce the behaviour/error
- Create a targeted survey
- Send messages to the server via Postman to an SMS endpoint
- When no more questions remain, observe the HTTP response from the server

#### Where does this issue happen?
- [x] [Local setup with Vagrant ](https://www.ushahidi.com/support/install-ushahidi#installing-for-development)
- [ ] [Local setup from platform-release ](https://www.ushahidi.com/support/install-ushahidi#installing-the-latest-release)
- [ ] Ushahidi.io / SaaS solution 
- [x] Ushahidi's QA environment
- [ ] Other (explain):

**Comment by kinstelli** [comment]
@rowasc -- Would you have a chance to confirm this issue?
Looking at the code, I think it's throwing an exception when there might not be any more questions remaining to be sent, but I'm not sure.

**Comment by rowasc** [comment]
@kinstelli did this have the latest code merged in? With the fixes for the message-receive to allow messages even if there's no survey, this wouldn't happen

**Comment by rowasc** [comment]
@kinstelli yea just checked. They are in `develop` :/  I was hoping there was a weird merge issue

**Comment by rowasc** [comment]
ugh trying to repro locally does not result in this bug :( checking qa now..

**Comment by rowasc** [comment]
@kinstelli ok so this happens when your contact WAS in a different survey before, as Mark suspected. 
The issue is in 
>		$surveyStateEntity = $this->targeted_survey_state_repo->getByContactId($contact_id);

where we just select one and not the one that's active

**Comment by rowasc** [comment]
@kinstelli @StaicyG @Eve-wanderi 
 This specific issue is solved now. 
@kinstelli because of https://app.zenhub.com/workspace/o/ushahidi/platform/issues/2795 if you use the test service you might run into issues. For instance , if you add numbers with + before country code (+59891222333) and send a message with test service, all is lost because it seems test service is stripping the + from country code at some point.  If when you add your number, you use the number without the country code, it finds the contact correctly because the test sms service is not doing anything weird to it. 
In any case, this makes #2795 our next top priority :/

**Comment by Eve-wanderi** [comment]
@rowasc  tried with a valid number without adding + but still cant get the sms. Am currently using SMSsync service is there any other test service i can use so as to get the sms?

**Comment by kinstelli** [comment]
@rowasc - I'm afraid I've never used SMSSync before, either -- just Twilio -- and I don't have a functioning Android phone to set this up. 

I believe that @aoduor agreed last week to help with Eve with a configuration of this, however.

**Comment by kinstelli** [comment]
Closing this since the initial problem is solved. Secondary issue mentioned in conversation appears related to #2795.
