### ISSUE TITLE
The Android App survey submit is failing occassionally

### ISSUE THREAD

**Issue by r-tock** [ushahidi/platform#3230]
**Screenshots**
<img width="265" alt="screen shot 2018-08-23 at 3 54 42 pm" src="https://user-images.githubusercontent.com/11711723/44554695-94e57a00-a6f7-11e8-8ee7-e692ee8b6b24.png">

**URL / Environment where this happened**
Android version of https://keralarescuemap.ushahidi.io/

**Comment by willdoran** [comment]
@r-tock was this fixed by the beta?

cc: @dalezak

**Comment by r-tock** [comment]
Yes this was fixed by the beta

**Comment by willdoran** [comment]
We're rushing to publish the beta will update when done

**Comment by dalezak** [comment]
@r-tock just to confirm, the Beta build fixed all issues of this problem? Or were you still experiencing some intermittent issues posting reports?

**Comment by r-tock** [comment]
Yes, The beta build fixed it.

**Comment by r-tock** [comment]
Please let us know once you have fixed the location issue in the Beta build and pushed it. We are going live in the morning in India, which is about 8-9 hours from now.

**Comment by rowasc** [comment]
@r-tock this should be solved in the latest release for android (it went out today for Android and should be available, it'll take some time before the app store approves in iOS) . 
Closing
