### ISSUE TITLE
Filter by "my posts" request

### ISSUE THREAD

**Issue by jshorland** [ushahidi/platform#388]
How do I find “my posts”

**Comment by jshorland** [comment]
@rjmackay -- i think this exists now. Can you confirm and close if so?

**Comment by rjmackay** [comment]
There's an saved search auto created to filter this.. but we don't actually show this in the filters list.
Probably worth adding. Might need some UI input

**Comment by jshorland** [comment]
Fixed. Closing.

**Comment by rjmackay** [comment]
@jshorland this isn't fixed as such. I guess its a question of: should we be able to filter by user?
There's a single "My posts" saved search. But you can't filter by my posts along with any other filters...

**Comment by jshorland** [comment]
There's a good use case for filtering posts by user (not member, user created by admin with an assigned role). 
Questions for scoping:
- [ ] what do we actually filter by? posts that they've created, posts that they've published, or some other task associated with the post?

- [ ] Do people need to filter within posts by a particular user? What's the user story there?

**Comment by rjmackay** [comment]
Duplicate of #2042
