### ISSUE TITLE
Filter by task

### ISSUE THREAD

**Issue by rjmackay** [ushahidi/platform#401]
Confirm issue seen previously where filtering by stages from multiple forms gives unexpected results.

**Comment by rjmackay** [comment]
@willdoran let me know if you need more debug info and I'll try to reproduce this again.

**Comment by willdoran** [comment]
any more info you can give would be handy, I'm working through them in seq order

**Comment by willdoran** [comment]
Ok, I think I've found the issue, multiple current_stage= params are being added to the geojson request - this also occurs for tags...is tags functioning as expected?

**Comment by rjmackay** [comment]
You should get `tags[]=1&tags[]=2` which PHP will parse into an array.. is that not happening?

**Comment by willdoran** [comment]
For geojson(map) filtering requests I'm getting 
geojson?order=desc&orderby=created&status=all&tags=4&tags=3

**Comment by rjmackay** [comment]
- I have a deployment with 2 post types: Test form, and Missing people, with posts of both types.
- I filter to Current step: missing people-main.

Expected result: see a list of missing people in stage main
Actual: List of all "test form" posts and "missing people in stage main"

**Comment by willdoran** [comment]
Ok I'm reproduced this the form_id filter is not behaving as expected, and is being superseded. I'm pulling the query apart to figure out why it's being ignored.

**Comment by willdoran** [comment]
Ok, I think this is now fixed but I'd like someone else to test it before I mark it closed.

**Comment by rjmackay** [comment]
Still broken, but differently.
- I have 2 posts - both complete step 1, one has complete step 3.. other hasn't. So current stage for both should be stage 2
- however 1 is returned for current stage = stage 2 and the other for current stage = stage 3

.. I don't think we're reliably getting the lowest priority stage to compare to. And I'm not clear at all how to resolve this within the limits of MySQL

**Comment by willdoran** [comment]
hmmmm ok, so I think I've recreated your setup
+---------------+---------+-----------+
| form_stage_id | post_id | completed |
+---------------+---------+-----------+
|             1 |      96 |         1 |
|             1 |      97 |         1 |
|             3 |      96 |         1 |
+---------------+---------+-----------+
so post 96 has completed 1 and 3 and current stage is therefore 2
post 97 has completed 1 and current stage is therefore 2
But when i filter by current stage is two, both are correctly returned :/ 
This doesn't seem to vary to any degree, unless it varies with install/setup

**Comment by rjmackay** [comment]
If you reorder stages so that stage id order doesn't match priority order is it still right?

**Comment by willdoran** [comment]
Ok, I've created another - may <insert entity of choice> have mercy on our souls - layer of sub clause. This appears to be behaving correctly. I'm worried that in reality it might be better to rethink the way the data model is stored. 

Possibly something more like as an explicit linked list.

**Comment by jshorland** [comment]
Need to retest. Assigning to myself.

**Comment by rjmackay** [comment]
Definitely still broken. We've remove the filter entirely from the UI though :)

**Comment by jshorland** [comment]
Tagging this to "tasks", because it will become important for people to be able to filter by which task they'd like to triage through.

**Comment by rowasc** [comment]
Closing as we don't have this filter anymore
