### ISSUE TITLE
Post Summary - top right gradient square

### ISSUE THREAD

**Issue by sophshep** [ushahidi/platform#658]
Gradient square in top right of post summary:
http://github.ushahidi.org/platform-pattern-library/assets/html/5_layouts/home-list.html

Confirmed that this is caused by overflow scrollbar: .categories-list-inline has overflow: auto

 Seen in both chrome (v44) and firefox (v39)

Note for @sophshep: Work on #657 first, it will likely fix this.

**Comment by sophshep** [comment]
I've removed any instances of `overflow:auto` so this should be fixed. I haven't been able to recreate the gradient.

Please reopen this issue if you see it again anywhere.

**Comment by rjmackay** [comment]
I'm still seeing these on post summary and post detail:
https://www.dropbox.com/s/vskeqokqv57m8pq/Screenshot%202015-09-08%2010.57.04.png?dl=0
https://www.dropbox.com/s/gfol5yq3yqz03dr/Screenshot%202015-09-08%2010.54.16.png?dl=0
