### ISSUE TITLE
Reset password "Invalid Token" + Non clickable link in email

### ISSUE THREAD

**Issue by aoduor** [ushahidi/platform#788]
Steps to reproduce:-
* Click on reset password and add appropriate email address

Expected outcome
* Email with link to reset password received in mailbox
* reset password link should redirect to page to create a new password
OR
* Password reset token entry results in successful reset password.

Actual outcome
* Reset password link received via email is not clickable
* I entered the reset password token and tried to reset and got a response that my token has expired or is invalid(just about a minute after sending the request)

**Comment by aoduor** [comment]
Tried it a second time - same response.

**Comment by rjmackay** [comment]
Should be fixed as soon as the migrations finish running (5 mins)

**Comment by aoduor** [comment]
Okidoks - the password token works out fine now, BUT - the "Reset Password" link that comes through via email is still not clickable. Shall i create another issue or just reopen this one?

**Comment by rjmackay** [comment]
Can you screenshot? the button is clickable for me..

**Comment by aoduor** [comment]
@rjmackay confirmed that this is a bug with my mail app and not the platform itself... Ignore :D.
